config/routes.rb
Exportling::Engine.routes.draw do
  # TODO: Consider allowing #new to accept POST requests
  #       Params supplied to #new may exceed GET length limits
  resources :exports do
    member do
      get :download
      get :retry
    end
  end

  root to: 'exports#index'
end

app/models/exportling/export.rb
class Exportling::Export < ActiveRecord::Base
  belongs_to :owner, class_name: Exportling.export_owner_class.to_s

  validates :name, presence: true
  validates :klass, presence: true
  validates :file_type, presence: true

  serialize :params

  mount_uploader :output, Exportling::ExportUploader

  # Sidekiq worker class that will perform the export
  def worker_class
    klass.constantize
  end

  # Which class should we try to authorize export permissions against?
  # Only needed when using Pundit
  def authorize_on_class
    class_name = worker_class.authorize_on_class_name
    class_name.constantize if class_name.present?
  end

  def completed?
    status == 'completed'
  end

  def incomplete?
    !completed?
  end

  def failed?
    status.downcase == 'failed'
  end

  def processing?
    status == 'processing'
  end

  def processed?
    %w{failed completed}.include?(status)
  end

  def file_missing?
    !file_exists?
  end

  def file_exists?
    output.file.try(:exists?)
  end

  def file_name
    "#{id}_#{name.parameterize}_#{created_at.strftime('%Y-%m-%d')}" +
    Exportling.export_file_name_suffix + ".#{file_type}"
  end

  def set_processing!
    update_attributes(status: 'processing',
                      started_at: Time.zone.now)
  end

  def complete!
    update_attributes(status: 'completed',
                      completed_at: Time.zone.now)
  end

  def fail!
    update_attributes(status: 'failed',
                      completed_at: Time.zone.now)
  end

  # Perform the export
  def perform!
    worker_class.perform(id)
  end

  # Perform the export as a background job with Sidekiq
  def perform_async!
    worker_class.perform_async(id)
  end
end

app/controllers/exportling/application_controller.rb
class Exportling::ApplicationController < ApplicationController
  helper Exportling::ApplicationHelper

  # Skip cancan authorization if used
  # TODO: Should be able to use cancan to authorize exports
  if respond_to?(:skip_authorization_check)
    skip_authorization_check
  end

  # prepended with underscore to reduce likelihood of naming conflicts
  def _current_export_owner
    send(Exportling.export_owner_method)
  end

  def using_pundit
    Exportling.authorization_mechanism == :pundit
  end
end

app/controllers/exportling/exports_controller.rb
# TODO: Ensure all exports scoped to owner
class Exportling::ExportsController < Exportling::ApplicationController
  before_action :load_and_authorize_export, only: [:download, :retry]

  decorates_assigned :export

  def index
    # query = params[:q] || {}
    # query.merge({ owner_id_eql: current_export_owner.id })
    # @query = Exportling::Export.ransack(query)
    # exports = @query.result.page(params[:page] || 1)
    exports = using_pundit ? policy_scope(exports_scope) : exports_scope
    @exports = Exportling::ExportsDecorator.decorate(exports)
  end

  def new
    # TODO: Improve how klass is specified
    #        The current method of including it in hidden fields opens it
    #        up to user tampering
    @export = ExportCreator.new(export_params, _current_export_owner).perform
    authorize_new_export

    unless @export.valid?
      fail ArgumentError, @export.decorate.invalid_attributes_message
    end
  end

  def create
    @export = ExportCreator.new(export_params, _current_export_owner).perform
    authorize_new_export

    unless @export.valid?
      fail ArgumentError, @export.decorate.invalid_attributes_message
    end

    # Save the export and start it processing
    @export.save
    @export.perform_async!

    redirect_to root_path
  end

  def download
    if @export.nil?
      flash[:error] = I18n.t('exportling.export.download.not_found')
      redirect_to root_path
    elsif @export.incomplete?
      flash[:error] = I18n.t('exportling.export.download.incomplete')
      redirect_to root_path
    elsif @export.file_missing?
      flash[:error] = I18n.t('exportling.export.download.missing')
      redirect_to root_path
    else
      redirect_to  @export.output.url
    end
  end

  def retry
    @export.status = 'created'
    @export.save
    @export.perform_async!

    flash[:message] = I18n.t('exportling.export.retry')
    redirect_to root_path
  end

  private

  def load_and_authorize_export
    @export = Exportling::Export.find_by(id: params[:id],
                                         owner_id: _current_export_owner.id)

    authorize(@export) if using_pundit
  end

  def authorize_new_export
    return unless using_pundit

    if @export.authorize_on_class.nil?
      msg = "You must pass a class name to authorize_on_class in your exporter"
      raise ArgumentError, msg
    end

    authorize(@export.authorize_on_class, :export?)
  end

  def export_params
    ExportRequest.new(params.require(:export).permit!).to_hash
  end

  def exports_scope
    Exportling::Export.where(owner_id: _current_export_owner.id)
                                     .order(created_at: :desc)
                                     .page(params[:page] || 1)
  end
end

app/helpers/exportling/application_helper.rb
module Exportling
  module ApplicationHelper
    def method_missing(method, *args, &block)
      main_app.send(method, *args)
    end
  end
end

app/views/exportling/exports/_export.html.erb
<tr>
  <td><%= export.id %></td>
  <td><%= export.name %></td>
  <td><%= export.file_name %></td>
  <td><%= export.file_type %></td>
  <td><%= export.created_at %></td>
  <td><%= export.updated_at %></td>
  <td><%= export.elapsed %></td>
  <td><%= export.status.capitalize %></td>
  <td><% if export.completed? %>
    <%= link_to 'Download', download_export_path(export) %><% end %>
   <% if export.failed? %>
    <%= link_to 'Retry', retry_export_path(export) %><% end %>
  </td>
</tr>

app/views/exportling/exports/_form.html.erb
<%= form_for @export do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :klass %>
  <%= hash_to_hidden_fields({ export: { params: @export.params } }) %>
  <%= f.hidden_field :file_type %>
  <%= f.submit %>
<% end%>

app/views/exportling/exports/create.html.erb
<%= render 'form' %>

app/views/exportling/exports/index.html.erb
<h2>Exports</h2>

<p>Your recently created exports</p>

<% unless @exports.empty? %>
  <table class="table table-striped">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>File Name</th>
      <th>Type</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Elapsed</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    <%= render @exports %>
  </table>

  <%= paginate @exports %>
<% else %>
  <p>No Exports Found</p>
<% end %>

app/views/exportling/exports/new.html.erb
<h3>Create Export</h3>

<p>Are you sure you want to create an export for <%= @export.name %>?</p>

<%= render 'form' %>